### ISSUE TITLE
Return hash in wallet.transfer and add send_message_return_hash method

### ISSUE THREAD

**Issue by lapismyt** [yungwine/pytoniq#36]
I know that exists two request types for sending message (pytonlib supports both): raw.sendMessage & raw.sendMessageReturnHash.

Please, add ability to get hash after sending message !

**Comment by yungwine** [comment]
Unfortunately I can't do that because of backward compatibility. But you can redefine `LiteClient`'s `raw_send_message` method so it returns cell hash:

```python
    async def raw_send_message(self, message: bytes):
        data = {'body': message}

        result = await self.liteserver_request('sendMessage', data)
        
        return Cell.one_from_boc(message).hash
```
